# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('0', 'qqq'), ('1', 'qq'), ('2', 'xx'), ('3', 'as'), ('4', 'ds')], default='1', max_length=4)),
                ('mobile', models.CharField(blank=True, default='', max_length=32, null=True, unique=True)),
                ('message_text', models.CharField(blank=True, default=None, max_length=2046, null=True)),
                ('need_notice', models.BooleanField(default=False)),
            ],
        ),
    ]
